<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManagedWimLib" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsImageDownloader.Wim\WindowsImageDownloader.Wim.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Oscdimg\oscdimg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>oscdimg.exe</Link>
    </None>
  </ItemGroup>

</Project>
